### ISSUE TITLE
Default 3P camera used in VR

### ISSUE THREAD

**Issue by Elttob** [Elttob/roblox-vr-tracker#22]
When using the default camera scripts, the regular third person camera/controls are used. Your head will be positioned following your character from an angle above, instead of using a proper VR camera. This can lead to serious motion sickness.

This may be fully worked around by implementing your own first person camera solution.

**Comment by LoganDark** [comment]
You can click the right stick to switch back to first-person mode. I do think the default should be changed however.

**Comment by Elttob** [comment]
This is now resolved.
