### ISSUE TITLE
New Roblox CoreGui menu lacks VR toggle

### ISSUE THREAD

**Issue by Elttob** [Elttob/roblox-vr-tracker#3]
There is no option to enable or disable VR mode in Roblox's (currently unreleased) new Settings UI in-game.

![image](https://user-images.githubusercontent.com/11815374/124568708-1ca6d900-de3d-11eb-8259-685ac42b008d.png)
![image](https://user-images.githubusercontent.com/11815374/124568718-203a6000-de3d-11eb-8a3e-5724a59e1e5f.png)

**Comment by p0s0** [comment]
I can probably add this myself by tinkering with the CoreScripts. I'll see what I can do here.

**Comment by Elttob** [comment]
> I can probably add this myself by tinkering with the CoreScripts. I'll see what I can do here.
> 
> EDIT: This is toggled by FFlagInGameMenuVRToggle. It's already set to false on join, but doesn't seem to exist in the official FFlags. It's registered on Line 46 in Modules/InGameMenu/Components/GameSettingsPage/BasicPage.lua, and is used for adding a toggle on Lines 177 - 184. Just wait for Roblox to enable this FFlag. You can probably close this for the time being.

Thanks - I'll add a label on for now, but I'll keep the issue open until it's fully rolled out 🙂

**Comment by Elttob** [comment]
Seems to be fixed :)
